<a href="https://colab.research.google.com/github/Anurag-sid/MS-AICTE-Movies-Recommendation-System-Project/blob/main/Movies_Recommendation_System_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
data = pd.read_csv('/content/movies.csv')
data.head(2)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   

                                       homepage     id  \
0                   http://www.avatarmovie.com/  19995   
1  http://disney.go.com/disneypictures/pirates/    285   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500

In [20]:
data = data.reset_index()

In [21]:
data.shape

(4803, 21)

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   index                 4803 non-null   int64  
 1   budget                4803 non-null   int64  
 2   genres                4803 non-null   object 
 3   homepage              1712 non-null   object 
 4   id                    4803 non-null   int64  
 5   keywords              4803 non-null   object 
 6   original_language     4803 non-null   object 
 7   original_title        4803 non-null   object 
 8   overview              4800 non-null   object 
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object 
 11  production_countries  4803 non-null   object 
 12  release_date          4802 non-null   object 
 13  revenue               4803 non-null   int64  
 14  runtime               4801 non-null   float64
 15  spoken_languages     

In [23]:
data.isnull().sum()

index                      0
budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                    0
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [24]:
selected_features = ['genres','keywords','tagline']
print(selected_features)

['genres', 'keywords', 'tagline']


In [25]:
for feature in selected_features:
  data[feature] = data[feature].fillna('')

In [26]:
combined_features = data['genres']+' '+data['keywords']+' '+data['tagline']
print(combined_features)

0       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3       [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
                              ...                        
4798    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4799    [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4800    [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4801                       [] [] A New Yorker in Shanghai
4802    [{"id": 99, "name": "Documentary"}] [{"id": 15...
Length: 4803, dtype: object


In [27]:
combined_features.name

In [28]:
combined_features = combined_features.astype(str).str.replace('nan', '')


In [29]:

vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)
print(feature_vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 147896 stored elements and shape (4803, 19291)>
  Coords	Values
  (0, 13945)	0.40595095836155964
  (0, 6948)	0.039156354201741336
  (0, 15393)	0.40595095836155964
  (0, 9972)	0.038948138264620964
  (0, 660)	0.04520272093559322
  (0, 10013)	0.044761863991448575
  (0, 931)	0.05531695180786814
  (0, 12864)	0.05464702381899983
  (0, 9583)	0.05156933410909896
  (0, 17080)	0.05133006465887894
  (0, 12954)	0.05135978020082438
  (0, 1024)	0.10932449364388583
  (0, 11912)	0.10044102941432208
  (0, 11439)	0.10828217119671589
  (0, 7041)	0.09053915153912896
  (0, 13211)	0.07789728098413677
  (0, 7433)	0.13531754761982834
  (0, 17591)	0.3115891239365471
  (0, 18946)	0.11929904096522384
  (0, 7442)	0.12163335461766618
  (0, 11544)	0.11292834957947866
  (0, 7670)	0.12163335461766618
  (0, 17527)	0.09564030064172369
  (0, 7727)	0.10242110503643924
  (0, 18464)	0.08003190699608956
  :	:
  (4800, 6723)	0.21517645638067023
  (4800, 15408)	0.2

***Cosine Similarity***

In [30]:
similarity = cosine_similarity(feature_vectors)
print(similarity)

[[1.         0.33622781 0.26096609 ... 0.26614764 0.         0.18793274]
 [0.33622781 1.         0.25454511 ... 0.25652912 0.         0.17182781]
 [0.26096609 0.25454511 1.         ... 0.19299489 0.         0.14120104]
 ...
 [0.26614764 0.25652912 0.19299489 ... 1.         0.         0.14646562]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.18793274 0.17182781 0.14120104 ... 0.14646562 0.         1.        ]]


In [31]:
similarity.shape

(4803, 4803)

## ***Movie Recommendation System.***

In [32]:
movie_name = input("Enter your favourite movie name :")

list_of_all_titles = data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = data[data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

print("Movies Suggested for you :\n")


i=0
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = data[data.index == index]['title'].values[0]
  if(i<5):
    print(i,'.',title_from_index)
    i+=1

Enter your favourite movie name :iron man
Movies Suggested for you :

0 . Iron Man
1 . Iron Man 3
2 . Iron Man 2
3 . Ant-Man
4 . Captain America: Civil War


# *END*